### ISSUE TITLE
estimation of position along z direction is not accurate

### ISSUE THREAD

**Issue by zhuyijie88** [UMich-CURLY/cheetah_inekf_realtime#1]
I have trouble when apply this method to estimating the 6-dim pose of quadruped A1. Specifically, the estimation of position along z direction ( gravity direction) is not accurate in my experiments, which decays as quadruped keep troting and the acceleration baise at z direction reaches to about -0.17 . I noticed that there are no such functions as below figure in `RobotState.cpp` .  But I have set the value of covariances as the same with ones of this repository via inekf::NoiseParams.
![image](https://user-images.githubusercontent.com/17925255/144706428-acd324e5-00bf-4494-978a-9cd4f0903eb2.png)
  It is known that inaccurate estimation of z position may happen when only IMU data is available. However, with additional information, such as kinematics data and contact information, is it  possible to estimate the 6-dim pose enoughly ? Or, do I make mistakes somewhere ?  Please help .

**Comment by tzuyuan** [comment]
Hi,

Those functions exist in the "dev" branch in the InEKF repository: https://github.com/RossHartley/invariant-ekf/blob/devel/src/RobotState.cpp#L133. We apologize for the confusion and we'll update the readme for clarification. 

As for the drift in the Z direction, in theory, zero velocity measurements (contacts) on the feet can be used to correct the drift predicted from the IMU. However, inaccuracy in the kinematics model and false-positive contact estimation could contribute to inaccurate corrections and thus create drifts in the Z direction.

**Comment by zhuyijie88** [comment]
> 

Thank you for the reply.  Recently, I saw a paper "Legged Robot State Estimation in Slippery Environemtens Using Invariant Extended Kalman Filter with Velocity Update", where motors' velocity is used to build the measurment model for UPDATE STEP. It seems more informative then original INEKF method.

**Comment by tzuyuan** [comment]
Hi,

Indeed, the contact-aided invariant EKF uses the non-slip condition to correct the state. From our experiments, we observed that a better contact estimation can significantly reduce the height drift. You can find more information in our recently published paper [here](https://openreview.net/pdf?id=yt3tDB67lc5).

Many recent works relax the non-slip condition by using the foot velocity to correct the state. However, most of those works require an additional sensor, often a stereo camera, to allow the foot velocity to become observable. (For example, the work you pointed out uses a stereo camera to infer body velocity.) This work, on the other hand, focuses on using a purely proprioceptive approach, as vision sensors could potentially fail in certain environments. Nevertheless, I agree using the velocity is a more informative way and is an interesting future direction.

Please let me know if you have any further questions. If not, I will close this issue in 3 days. Thank you.
