### ISSUE TITLE
Looking forward to receiving a data package, thank you very much

### ISSUE THREAD

**Issue by 1219883141** [UMich-CURLY/cheetah_inekf_realtime#2]
Hi, can I get your (synced_proprioceptive_lcmt).data package mentioned in https://github.com/UMich-CURLY/cheetah_inekf_realtime/blob/main/src/communication/lcm_handler.cpp， I checked your data folder LCM file, which should be the packet of the previous version,

**Comment by tzuyuan** [comment]
Hi,

synced_proprioceptive_lcmt message is the output from our [deep contact estimator](https://github.com/UMich-CURLY/deep-contact-estimator). If you would like to run the synchronized version, we have another repository where you can use your own customize contact information: [cheetah_inekf_lcm](https://github.com/UMich-CURLY/cheetah_inekf_lcm).

As for the height drift issue, from our experiments, we observed that a better contact estimation (fewer false-positive contact events) can reduce the height drift significantly. We conjure the violation of zero-velocity constraints on the foot to be one of the main factors that contribute to the height drift.
